source 'https://rubygems.org'

gem 'rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier'
end

gem 'jquery-rails'
gem "airbrake"

group :test do
  gem "rspec-rails"
  gem "cucumber-rails", require: false
  gem "launchy"
  gem "capybara"
  gem "database_cleaner"
  gem "spork", "~> 0.9.0.rc"
  gem "mocha"
  gem "factory_girl"
  gem "email_spec"
  gem 'sqlite3'
  gem "pry-rails"
end


gem "pg", :group => "production"
gem "thin"

group :development do
  gem "letter_opener"
  gem "sqlite3"
  gem "pry-rails"
end
